### PR TITLE
Added new error message. Addresses #73.

### PR DESCRIPTION
**Pull request by ashryanbeats**

### CODE REVIEW

**Comment by kerrishotts** [comment]
Moved to Sprint 2; didn't get merged

**Review by kerrishotts — APPROVED** [review]
LGTM

**Comment by kerrishotts** [comment]
@ashryanbeats This will be picked up in next deploy. ash/sprint-1 branch merged & deleted.

**Comment by ashryanbeats** [comment]
Looks like it was deployed, so I'll move this card on the project.

**Pull request merged**
